# Generated by Django 3.0.8 on 2020-07-24 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('dimenstions', models.FloatField()),
                ('delivery_type', models.CharField(choices=[('STD', 'Standard'), ('EXP', 'Express')], max_length=30)),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True)),
                ('order_status', models.CharField(choices=[('RTS', 'Ready to ship'), ('SH', 'Shipped'), ('DL', 'Delivered'), ('CN', 'Cancelled'), ('RFD', 'Returned Failed Delivery')], max_length=50)),
                ('delivery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.Delivery')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=50)),
                ('highlight', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=12)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('buyer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warranty_type', models.CharField(choices=[('IMW', 'International manufacturer warranty'), ('NW', 'No Warranty'), ('GN', 'Guarantee')], max_length=50)),
                ('warranty_period', models.IntegerField()),
                ('policy', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.BooleanField()),
                ('quantity', models.IntegerField()),
                ('sproduct', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=200)),
                ('star', models.CharField(choices=[('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')], max_length=50)),
                ('productreview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Product'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=30)),
                ('products', models.ManyToManyField(to='account.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberofitem', models.IntegerField()),
                ('subtotal', models.FloatField()),
                ('total_cost', models.FloatField()),
                ('dcost', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.Delivery')),
                ('prices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Product')),
            ],
        ),
    ]
