# Generated by Django 3.0.8 on 2020-07-24 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='dcost',
            new_name='delivery',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='prices',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='products',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='cat_name',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='buyer',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='productreview',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='sproduct',
            new_name='product',
        ),
    ]
